- hosts: localhost
  gather_facts: no
  vars:
    gcp_region: us-east1
    gcp_zone: us-east1-b
    gcp_project: true-entropy-221110
    gcp_cred_kind: serviceaccount
    gcp_cred_file: ../credentials.json
    source_image: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20181030

  roles:
    #create network
    - role: gcp-network

    #create deploy machine
    - role: gcp-instance
      vars:
        gcp_machine_type: n1-standard-1
        external_ip: false
        instances:
          - { index: 1, tag: deploy }
        disk_size: 10
        disk_type: pd-standard
        type: deploy
  tasks: 
    - name: copy key
      copy:
        src: ~/.ssh/deployment
        dest: /Users/luisferreira/.ssh/deployment