- name: Install Redis Server
  apt:
    name: [redis-server]
    state: latest

#- name: Install Keepalived
#  apt:
#    name: ['keepalived']
#    state: latest

- name: Configuring Redis Server and Restart
  block:
    - template:
        src: slaveredis.conf.j2
        dest: /etc/redis/redis.conf
    - shell: |
        sudo adduser --disabled-login --gecos 'GitLab' git
        sudo mkdir /var/run/redis
        sudo chown redis:redis /var/run/redis
        sudo chmod 755 /var/run/redis
        if [ -d /etc/tmpfiles.d ]; then
          echo 'd  /var/run/redis  0755  redis  redis  10d  -' | sudo tee -a /etc/tmpfiles.d/redis.conf
        fi
        sudo usermod -aG redis git
        sudo service redis-server restart

- name: Configuring Redis Sentinel
  block:
    - template:
        src: redissentinel.conf.j2
        dest: /etc/redis/sentinel.conf


- name: Running Redis Sentinel
  shell: |
    sudo chmod +rw /etc/redis/sentinel.conf
    sudo redis-server /etc/redis/sentinel.conf --sentinel &
